# Generated by Django 5.2 on 2025-12-06 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物品类型',
                'verbose_name_plural': '物品类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('description', models.TextField(verbose_name='物品描述')),
                ('transaction_type', models.CharField(choices=[('GIFT', '赠送'), ('SELL', '出售')], max_length=4, verbose_name='交易类型')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格(出售时填写)')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系人邮箱')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系人手机')),
                ('dynamic_attributes', models.JSONField(blank=True, default=dict, verbose_name='动态属性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='物品图片')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemtype', verbose_name='物品类型')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='属性名称')),
                ('field_type', models.CharField(choices=[('char', '文本'), ('text', '长文本'), ('number', '数字'), ('date', '日期')], max_length=10, verbose_name='字段类型')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='items.itemtype', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '属性字段',
                'verbose_name_plural': '属性字段',
                'ordering': ['order'],
                'unique_together': {('item_type', 'name')},
            },
        ),
    ]
