# Generated by Django 5.2 on 2025-10-16 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('description', models.TextField(verbose_name='物品描述')),
                ('item_type', models.CharField(choices=[('GIFT', '赠送'), ('SELL', '出售')], max_length=4, verbose_name='交易类型')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格(出售时填写)')),
                ('contact_info', models.CharField(max_length=200, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='物品图片')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-created_at'],
            },
        ),
    ]
