# Generated by Django 5.2 on 2025-12-04 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='book_attributes', serialize=False, to='items.item')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('edition', models.CharField(blank=True, max_length=20, verbose_name='版本')),
            ],
            options={
                'verbose_name': '书籍属性',
                'verbose_name_plural': '书籍属性',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_attributes', serialize=False, to='items.item')),
                ('expiry_date', models.DateField(verbose_name='保质期')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('storage_condition', models.CharField(blank=True, max_length=100, verbose_name='储存条件')),
            ],
            options={
                'verbose_name': '食品属性',
                'verbose_name_plural': '食品属性',
            },
        ),
        migrations.CreateModel(
            name='ToolItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tool_attributes', serialize=False, to='items.item')),
                ('condition', models.CharField(max_length=50, verbose_name='使用状况')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='型号')),
            ],
            options={
                'verbose_name': '工具属性',
                'verbose_name_plural': '工具属性',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='物品所在地址'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category', verbose_name='物品类别'),
        ),
    ]
