# Generated by Django 5.2 on 2025-12-04 09:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('items', '0002_bookitem_category_fooditem_toolitem_item_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品类型名称')),
                ('attributes', models.JSONField(default=list, verbose_name='动态属性定义')),
            ],
            options={
                'verbose_name': '物品类型',
                'verbose_name_plural': '物品类型',
            },
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='toolitem',
            name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='item',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='联系人邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='contact_phone',
            field=models.CharField(default='1', max_length=20, verbose_name='联系人手机'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='dynamic_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='动态属性'),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(max_length=200, verbose_name='物品所在地址'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='物品说明'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.TextField(blank=True, verbose_name='住址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已批准')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemtype', verbose_name='物品类别'),
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='ToolItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
